### PR TITLE
Default player interaction map test

### PR DESCRIPTION
**Pull request by BCrlrd**
This adds almost all tests for Default player interaction map.
One branch isn't tested because it creates a ResourcesWrapper, thus testing this would require us to refactor the handler.

< testing

### CODE REVIEW

**Comment by Pathemeous** [comment]
Great work, must have been a lot of effort!

One comment I have is that you might want to name all tests after what they actually test, rather than numbering them. This way we know what functionality each collision has, whether it has been tested, and whether it still works. This is especially useful for the new Bubble implementations, to verify that no old collisions are broken.

< naming, testing

**Comment by BCrlrd** [comment]
I will rename them. Shouldn't be too much effort.

< testing, naming

**Comment by BCrlrd** [comment]
I have renamed all tests and added comments for tests which might become confusing without them.

< naming, testing, documentation

**Comment by Pathemeous** [comment]
Looks great! I have no further comments, so I am merging this.

< review

**Pull request merged**
