### PR TITLE
Improvement/state managing

### PR DESCRIPTION
**Pull request by justinvdk**
To prevent accidental conflicts or a lot of manual refactoring, added a States class to hold the IDs of the GameStates.

< layout

### CODE REVIEW

**Comment by justinvdk** [comment]
Fixing tests....

**Comment by justinvdk** [comment]
tests fixed < testing

**Comment by BCrlrd** [comment]
I have a feeling one state is missing, as the ID of GameEndedState was 6 but has been changed to 5.

< review

**Comment by BCrlrd** [comment]
Ah I see you have split the multiplayer settings to use the same state.
The code looks fine, I'll run it and if it works as normal I will merge.

< review

**Comment by justinvdk** [comment]
That is correct. With the splitting of Game into SingleplayerGame and MultiplayerGame this was not needed anymore.

**Pull request merged**
