### PR TITLE
Countdown

### PR DESCRIPTION
**Pull request by cathmer4**
Creates a countdown before the start of each level.

### CODE REVIEW

**Comment by Pathemeous** [comment]
Not sure how all these previous commits that should already be in <code>development</code> got into this PR's diff, but I'm gonna assume that it works out.

The code looks very neat and to the point.
One comment that I have is the decision for a Countdown per <code>Game</code> vs. a countdown per <code>Level</code>. My gut says it's more OO create a new instance of the object instead of resetting it. I don't see how it matters at all, but I wonder what ideas you have about this and why (if at all) you chose for <code>Game</code>.

Despite this question, I think it can be merged.

< review, organisation, interface

**Comment by cathmer4** [comment]
The previous commits are in here because I branched out of my other branch, because I wanted to make it with that implementation already there, because some things might conflict during implementation. 

I have to admit that I didn't know until just now that a new instance of Level is made each time the player dies, so I thought it wasn't possible at all to put the countdown in level. However, now that I know, it's still not possible, because countdown needs to pause the level and the player, so it needs an instance of game. If it would only pause everything in Level, the Player would still be able to walk. 

Also, while looking into this, I noticed that all levels get initialised twice when the application is started, and another time when a new game is started. This is something I will look into now.

**Comment by Pathemeous** [comment]
Right, that is rather obvious.

The levels might be initialised twice when the application is started because the two <code>GameState</code>s are (wrongfully) already loaded and therefore create a game with levels. The objects are then collected by the GC since they aren't used.

p.s. don't forget tags.

< performance, bug

**Comment by cathmer4** [comment]
I fixed the initialisation thing, gamestate isn't initialised until user starts a single or multi player game. So this branch is ready to be merged.

**Pull request merged**
