### PR TITLE
Projectile

### PR DESCRIPTION
**Pull request by BCrlrd**
This works as expected, which means I think it can be merged into the master.

### CODE REVIEW

**Comment by BCrlrd** [comment]
Well you know, if you ignore the whole "ball" part, which can just be removed.

**Comment by Pathemeous** [comment]
Could you please add JavaDoc to the code? This will save us a lot of hassle later trying to add the right comments and understanding the code of others

**Comment by BCrlrd** [comment]
Sure. I don't have checkstyle up and running yet so it might not have the correct markup, but it'll be there.

**Comment by BCrlrd** [comment]
Build fails according to travis. This is probably the case because I do not have travis installed yet (in a train, internet is shit).

**Comment by Pathemeous** [comment]
it uses the default build (which is for Ruby) because you don't have the travis.yml file. I'll merge it

**Comment by BCrlrd** [comment]
Well that makes sense. Once this is added to the master I'll clone the repo again, which means I'll have the right configs now that we have them up and running.

**Comment by Pathemeous** [comment]
We just decided to wait with merging this branch. The reason is that it does work, but the structure seems very confusing to us. It doesn't seem to comply with the UML structure that we created last week (if it does, we don't understand it). So we will merge it tomorrow when we meet in Delft.

**Comment by BCrlrd** [comment]
I forgot we made an UML structure for this, which might explain why it doesn't comply with it.

**Pull request closed without merging**
