### PR TITLE
Shop fixes

### PR DESCRIPTION
**Pull request by cathmer4**
fixes most of the bugs from the shop items.

### CODE REVIEW

**Comment by Pathemeous** [comment]
Looks great. We should have a test suite that exposes these bugs, especially the simple corner-case failures like buying with exactly enough money.

Also seeing now that testability with the <code>ResourceWrapper</code> might still be hard. Instead of passing a new <code>ResourceWrapper</code> each time we need one, we might want to consider making it a Singleton. This way we don't need to pass it along through the methods, but we can still mock it (by mocking the <code>getInstance()</code> method to return a mocked <code>ResourceWrapper</code> instead of a real one).

< testing, organisation, interface

**Comment by cathmer4** [comment]
Why is testing still hard?

**Comment by Pathemeous** [comment]
Because the applyTo method for instance creates a Weapon with a new
ResourceWrapper. We cannot inject a mock there so that method will always
crash in Travis.

**Comment by cathmer4** [comment]
We could also make a WeaponFactory which creates Weapons, and then mock this WeaponFactory and let it return a mockedweapon.

**Comment by Pathemeous** [comment]
that would actually be a good structure yeah. Then we can have the
WeaponFactory use the resources and we only have that dependency in one
location.
We should have a look at the design patterns regarding object creation and
pick one that can be accessed globally, without needing dependency
injection, yet can be injected during testing.

**Pull request merged**
