### PR TITLE
Improved keybindings

### PR DESCRIPTION
**Pull request by cathmer4**
Improved the way the key bindings are read and stored in a file. The structure is still not perfect, but it's already more readable and more robust than it was.

### CODE REVIEW

**Comment by BCrlrd** [comment]
Could @Pathemeous confirm this works with his code?

< review

**Comment by Pathemeous** [comment]
This change will not work.  My branch contains the required fix for settings but since I haven't pushed it you can't see it right now. When I get my laptop I will make sure to make the necessary changes and merge it.
(this change does improve structure, I just need to change a few lines). 

< review

**Comment by cathmer4** [comment]
Oke great. Try to push your work more often so others now what you are working on.

**Comment by BCrlrd** [comment]
I second that request

**Comment by Pathemeous** [comment]
This branch was merged in #157.

**Pull request closed without merging**
