### PR TITLE
Menu

### PR DESCRIPTION
**Pull request by indisputable**
added a pause option with the escape button with the option to return to the main menu, at this moment if you press single player again, the game will be in the same state, this will be fixed when level and game class are up and running

### CODE REVIEW

**Comment by Pathemeous** [comment]
We should hold this one until the level and game branch is merged. This also changes a lot of content in GameState, so most likely a lot of conflicts will occur.

**Comment by BCrlrd** [comment]
You can blame Woutert for that

**Comment by indisputable** [comment]
Casper seemed to think otherwise, but I'll let you guys fight it out ;p

**Comment by cathmer4** [comment]
I think it's easier to merge this first and merge Wouter's branch afterwards, otherwise you'll have to fix merge conflicts multiple times.

**Comment by BCrlrd** [comment]
Wouter has merged the master into his branch, so there shouldn't be any conflicts because of his pull request.

**Comment by Pathemeous** [comment]
I haven't, but I will. Right now this pull request is already conflicting with Casper's, so I suggest either of you solves that.

**Pull request merged**
