### PR TITLE
Options extra

### PR DESCRIPTION
**Pull request by BCrlrd**
This PR contains the following features
* Ability to change logger severity from options menu.
* Ability to set key bindings from options menu.
* Ability to save/load key bindings to/from file.

Some of this code isn't as pretty as it could be. I blame slick for this, as it is terrible for handling key inputs if you don't know which inputs to expect (which is the case when setting keys). I have used a workaround for this. If anyone has a better idea, please let me know. Or of course, implement it. Unit tests will follow tomorrow.

< feature

### CODE REVIEW

**Comment by Pathemeous** [comment]
The states by themselves look great. We sadly won't be able to get test coverage on much of them because of Slick, but that is something that can't be changed.

I think the JSON format and the KeyBindHelper (which parses the JSON) could benefit from a better structure and clearer single-responsibiltiy respectively. The JSON right now doesn't actually utilize the strengths of JSON and the KeyBindHelper doesn't parse the file into completed objects, but only provides a list (that no other object really (should) know the structure of). In this case I believe the KeyBindHelper should have more responsibility than it currently has.

That being said, I believe we will have to accept this complexity for now, because the deadline is nearing and the first need to finish the documentation.

Other than those "wontfix" points, the code seems ready to merge. (I actually already branched off these commits and am using them already).

< review, organisation, documentation

**Comment by BCrlrd** [comment]
The reason it doesn't parse into full fledged objects right away is because the full fledged weren't there when I started working on the parser. We could move some of the creation methods for key bindings from the settings class to the KeyBindHelper class, if you think that would more evenly split the responsibility.

< review

**Comment by cathmer4** [comment]
You could just make methods getPlayer1Left, getPlayer2Left, etc. in the KeyBindHelper. This is not a lot of work and already makes it a lot clearer.

**Comment by BCrlrd** [comment]
Agreed. I currently have those methods in the settings class. I'll wait till @Pathemeous has fixed his code before moving the methods, as he's currently using those methods.

**Comment by cathmer4** [comment]
Do you mind if I change the way the JSON works? Because it's really not practical this way, defining your own key, and I don't think it's a lot of work to change it.

**Comment by BCrlrd** [comment]
Go for it. As I said I went for this method as that's the one that I knew how to use. Please ask @Pathemeous aswel as he's the one currently using it, so you might break his current code.

**Comment by Pathemeous** [comment]
Please refer to the issue instead, this PR is already closed.

But as long as the Settings PlayerInput are initialized once and persistent
as long as a game runs (scope of GameState), my code will work.

< review

**Pull request merged**
