### PR TITLE
Add Level Render Tests

### PR DESCRIPTION
**Pull request by Pathemeous**
Adds tests for the render method of Level.

This required setting the backGroundImage in the constructor, so that it can be mocked.

Because some Pickup tests did not use mocking to test their interaction with level, those broke and I fixed them by correctly mocking and verifying the calls made to the mocked Level object.

< testing, interface

### CODE REVIEW

**Comment by BCrlrd** [comment]
Did you test your bugfixes locally? Other than that everything looks fine.

< review

**Comment by Pathemeous** [comment]
I actually did not, but it is evident from the tests that your code never worked and does now.

: )

< testing

**Comment by BCrlrd** [comment]
I'm running this locally and will merge if everything indeed works fine, as I expect by looking at it.

< review

**Comment by BCrlrd** [comment]
As expected, this runs and looks great. Merging!

< review, testing

**Pull request merged**
