### PR TITLE
Start screen controller

### PR DESCRIPTION
**Pull request by Pathemeous**
Like all states, splits into a controller and adds testing where possible.

< testing

### CODE REVIEW

**Comment by cathmer4** [comment]
Could you try to achieve a higher line coverage on your tests? I feel like it's possible and you didn't put enough effort into it. < testing

**Comment by Pathemeous** [comment]
The buttons do not work in practice (the literally one thing that the tests do not test...).

I cannot resolve this tonight, so we will either have to close this PR or someone else needs to fix it.

< planning

**Comment by cathmer4** [comment]
I will take a quick look, and else I'll close it.

**Comment by cathmer4** [comment]
Wasn't able to fix it.

**Pull request closed without merging**
